apiVersion: apps/v1
kind: Deployment
metadata:
  name: stellar-connector
  namespace: hummingbot
  labels:
    app: stellar-connector
    version: v3.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stellar-connector
  template:
    metadata:
      labels:
        app: stellar-connector
    spec:
      containers:
      - name: stellar-connector
        image: stellar-connector:v3.0
        ports:
        - containerPort: 8000
        env:
        - name: STELLAR_NETWORK
          value: "mainnet"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5