apiVersion: v1
kind: Namespace
metadata:
  name: stellar-hummingbot
  labels:
    app.kubernetes.io/name: stellar-hummingbot-connector
    app.kubernetes.io/version: "3.0"
    app.kubernetes.io/component: namespace
    environment: production
    security.policy: restricted
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: stellar-hummingbot-quota
  namespace: stellar-hummingbot
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    pods: "20"
    services: "10"
    persistentvolumeclaims: "5"
    secrets: "20"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: stellar-hummingbot-network-policy
  namespace: stellar-hummingbot
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    - namespaceSelector:
        matchLabels:
          name: istio-system
    ports:
    - protocol: TCP
      port: 8080  # Metrics endpoint
    - protocol: TCP
      port: 8443  # HTTPS endpoint
  egress:
  - to: []  # Allow all egress (for Stellar network access)
    ports:
    - protocol: TCP
      port: 443   # HTTPS
    - protocol: TCP
      port: 80    # HTTP (for health checks)
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: UDP
      port: 53    # DNS
    - protocol: TCP
      port: 53    # DNS