# Stellar Hummingbot Connector - Enterprise Features Configuration
#
# This configuration file controls the activation and settings for enterprise-grade
# features in the Stellar connector. Features are organized by tier and business value.

# =============================================================================
# ENTERPRISE FEATURE ACTIVATION
# =============================================================================

enterprise_features:
  # Global settings
  validate_on_startup: true
  fail_fast_on_errors: false

  # =============================================================================
  # TIER 1: ENTERPRISE SECURITY FEATURES (CRITICAL)
  # =============================================================================
  security:
    # HashiCorp Vault Integration (748 lines)
    # Enterprise-grade key management and secrets storage
    vault_integration_enabled: false
    vault_config:
      vault_url: "https://vault.example.com:8200"
      auth_method: "TOKEN"  # TOKEN, USERPASS, APPROLE, KUBERNETES, AWS, AZURE
      engine_type: "KV_V2"
      mount_path: "stellar-secrets"
      # vault_token: "${VAULT_TOKEN}"  # Set via environment variable

    # Hardware Wallet Integration (712 lines)
    # Ledger and Trezor support for maximum security
    hardware_wallet_enabled: false
    hardware_wallet_config:
      supported_wallets: ["ledger", "trezor"]
      auto_detect: true
      timeout_seconds: 30
      require_confirmation: true

    # Security Hardening Framework (829 lines)
    # Production security controls and threat mitigation
    security_hardening_enabled: false
    security_hardening_config:
      security_level: "ENHANCED"  # MINIMAL, STANDARD, ENHANCED, MAXIMUM
      threat_monitoring: true
      access_control_enabled: true
      encryption_at_rest: true
      secure_communication: true

    # Security Metrics & Monitoring (758 lines)
    # Security event monitoring and compliance reporting
    security_metrics_enabled: false
    security_metrics_config:
      metrics_collection: true
      compliance_reporting: true
      alert_on_anomalies: true
      retention_days: 90

  # =============================================================================
  # TIER 2: ADVANCED TRADING & DEFI FEATURES (HIGH VALUE)
  # =============================================================================
  trading:
    # Advanced Liquidity Management (1,147 lines)
    # Professional liquidity management algorithms
    liquidity_management_enabled: false
    liquidity_management_config:
      strategy: "MARKET_MAKING"  # MARKET_MAKING, INVENTORY_BALANCING, CROSS_MARKET_ARBITRAGE
      risk_limits:
        max_position_size: 10000.0
        max_daily_loss: 1000.0
        max_concentration_risk: 0.3
      rebalancing:
        enabled: true
        frequency_minutes: 15
        threshold_percentage: 5.0

    # DeFi Yield Farming (1,116 lines)
    # Automated yield optimization strategies
    yield_farming_enabled: false
    yield_farming_config:
      strategy: "LIQUIDITY_MINING"  # LIQUIDITY_MINING, STAKING_REWARDS, COMPOUND_FARMING
      risk_tolerance: "MEDIUM"      # LOW, MEDIUM, HIGH
      max_risk_exposure: 0.2        # 20% of portfolio
      auto_compound: true
      harvest_frequency_hours: 24

  # =============================================================================
  # TIER 3: INFRASTRUCTURE & DEVELOPMENT TOOLS (MEDIUM VALUE)
  # =============================================================================
  infrastructure:
    # Test Account Manager
    # Automated test account management and funding
    test_account_manager_enabled: false
    test_account_config:
      friendbot_enabled: true
      auto_fund_threshold: 10.0    # XLM
      max_test_accounts: 50
      cleanup_after_hours: 72

    # Load Testing Framework
    # Performance and load testing capabilities
    load_testing_enabled: false
    load_testing_config:
      max_concurrent_connections: 100
      test_duration_minutes: 30
      ramp_up_time_minutes: 5
      monitoring_enabled: true

    # Performance Optimizer
    # Runtime performance optimization and tuning
    performance_optimizer_enabled: false
    performance_optimizer_config:
      auto_tuning: true
      memory_optimization: true
      connection_pooling: true
      cache_optimization: true

    # Web Assistant Utilities
    web_assistant_enabled: false

    # User Stream Tracker
    user_stream_tracker_enabled: false

# =============================================================================
# FEATURE DEPENDENCIES & VALIDATION
# =============================================================================

# Required credentials (set via environment variables)
required_credentials:
  vault_integration:
    - VAULT_TOKEN
    - VAULT_NAMESPACE  # Optional for Vault Enterprise
  hardware_wallet:
    - HW_WALLET_PIN    # Optional, for testing
  security_metrics:
    - METRICS_API_KEY  # Optional, for external metrics

# Resource limits per feature tier
resource_limits:
  security_tier:
    max_memory_mb: 200
    max_cpu_percent: 10
  trading_tier:
    max_memory_mb: 300
    max_cpu_percent: 20
  infrastructure_tier:
    max_memory_mb: 100
    max_cpu_percent: 5

# Feature compatibility matrix
compatibility:
  # Features that work well together
  recommended_combinations:
    - ["vault_integration", "hardware_wallet", "security_hardening"]
    - ["liquidity_management", "yield_farming"]
    - ["security_hardening", "security_metrics"]

  # Features that should not be enabled together
  conflicts:
    - ["load_testing", "liquidity_management"]  # Testing vs production

# =============================================================================
# EXAMPLE CONFIGURATIONS
# =============================================================================

# Example: Maximum Security Configuration
example_max_security:
  vault_integration_enabled: true
  hardware_wallet_enabled: true
  security_hardening_enabled: true
  security_metrics_enabled: true
  liquidity_management_enabled: false
  yield_farming_enabled: false

# Example: Professional Trading Configuration
example_professional_trading:
  vault_integration_enabled: true
  security_hardening_enabled: true
  liquidity_management_enabled: true
  yield_farming_enabled: true
  security_metrics_enabled: true

# Example: Development & Testing Configuration
example_development:
  test_account_manager_enabled: true
  load_testing_enabled: true
  performance_optimizer_enabled: true
  web_assistant_enabled: true
  security_features_enabled: false