apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: stellar-hummingbot-connector-hpa
spec:
  minReplicas: 3
  maxReplicas: 15
  metrics:
  # CPU-based scaling - more conservative in production
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  # Memory-based scaling - more conservative in production
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  # Custom metrics for production load
  - type: Pods
    pods:
      metric:
        name: stellar_concurrent_operations
      target:
        type: AverageValue
        averageValue: "150"
  - type: Pods
    pods:
      metric:
        name: stellar_request_rate_per_second
      target:
        type: AverageValue
        averageValue: "200"
  - type: Pods
    pods:
      metric:
        name: stellar_active_orders_count
      target:
        type: AverageValue
        averageValue: "100"
  # Business metrics scaling
  - type: Object
    object:
      metric:
        name: stellar_trading_volume_xlm_per_minute
      target:
        type: Value
        value: "500"
      describedObject:
        apiVersion: v1
        kind: Service
        name: stellar-hummingbot-connector-service
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600  # 10 minutes - more conservative
      policies:
      - type: Percent
        value: 20  # Scale down max 20% at a time
        periodSeconds: 120
      - type: Pods
        value: 2  # Scale down max 2 pods at a time
        periodSeconds: 120
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 120  # 2 minutes
      policies:
      - type: Percent
        value: 100  # Scale up max 100% at a time
        periodSeconds: 60
      - type: Pods
        value: 4  # Scale up max 4 pods at a time
        periodSeconds: 60
      selectPolicy: Max
---
apiVersion: autoscaling/v2
kind: VerticalPodAutoscaler
metadata:
  name: stellar-hummingbot-connector-vpa
spec:
  updatePolicy:
    updateMode: "Auto"  # Auto-update in production
  resourcePolicy:
    containerPolicies:
    - containerName: stellar-connector
      minAllowed:
        cpu: 250m
        memory: 512Mi
      maxAllowed:
        cpu: 2000m
        memory: 4Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits
      # Production-specific resource recommendations
      maxAllowedGrowth:
        cpu: 100%
        memory: 100%
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: stellar-hummingbot-connector-pdb
spec:
  minAvailable: 2  # Always keep at least 2 instances running
  selector:
    matchLabels:
      app: stellar-hummingbot-connector