apiVersion: v1
kind: Secret
metadata:
  name: stellar-secrets
  labels:
    app: stellar-hummingbot-connector
type: Opaque
stringData:
  # Application secrets (base64 encoded in production)
  secret-key: "your-secret-key-here"
  
  # Database connection
  database-url: "postgresql://stellar_user:stellar_password@postgres:5432/stellar_hummingbot"
  database-username: "stellar_user"
  database-password: "stellar_password"
  
  # Redis connection
  redis-url: "redis://:stellar_redis_password@redis:6379/0"
  redis-password: "stellar_redis_password"
  
  # Stellar network secrets
  stellar-secret-key: "YOUR_STELLAR_SECRET_KEY_HERE"
  stellar-public-key: "YOUR_STELLAR_PUBLIC_KEY_HERE"
  
  # HSM configuration
  hsm-pin: "your-hsm-pin"
  hsm-label: "stellar-trading-key"
  
  # External API keys
  coingecko-api-key: "your-coingecko-api-key"
  coinmarketcap-api-key: "your-coinmarketcap-api-key"
  
  # Notification webhooks
  slack-webhook-url: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
  discord-webhook-url: "https://discord.com/api/webhooks/YOUR/WEBHOOK"
  
  # Monitoring credentials
  grafana-admin-password: "secure-grafana-password"
  prometheus-auth-token: "your-prometheus-token"
  
  # SSL/TLS certificates (if using custom certs)
  tls-cert: |
    -----BEGIN CERTIFICATE-----
    # Your TLS certificate here
    -----END CERTIFICATE-----
  tls-key: |
    -----BEGIN PRIVATE KEY-----
    # Your TLS private key here
    -----END PRIVATE KEY-----
  
  # Backup encryption keys
  backup-encryption-key: "your-backup-encryption-key"
  
  # Third-party service credentials
  aws-access-key-id: "your-aws-access-key"
  aws-secret-access-key: "your-aws-secret-key"
  
  # JWT signing keys
  jwt-secret: "your-jwt-signing-secret"
  
  # Vault integration (if using HashiCorp Vault)
  vault-token: "your-vault-token"
  vault-role-id: "your-vault-role-id"
  vault-secret-id: "your-vault-secret-id"